type = "sdram"
name = "Mini ISSI"

data_bits = 16
row_bits = 6
col_bits = 4
bank_bits = 1
auto_precharge_bit = 5

[timing.cl2]
t_ck = { min = 7.5 }
t_rc = { min = 60 }
t_ras = { min = 37, max = 100_000 }
t_rp = { min = 15 }
t_rcd = { min = 15 }
t_mrd = { min = 14 }
t_dde = { min = 7 }
t_xsr = { min = 70 }
t_ref = { max = 64_000_000 }

[timing.cl3]
t_ck = { min = 7 }
t_rc = { min = 60 }
t_ras = { min = 37, max = 100_000 }
t_rp = { min = 15 }
t_rcd = { min = 15 }
t_mrd = { min = 14 }
t_dde = { min = 7 }
t_xsr = { min = 70 }
t_ref = { max = 64_000_000 }
